### ISSUE TITLE
removeEvent()  FATAL EXCEPTION

### ISSUE THREAD

**Issue by sunxd** [SundeepK/CompactCalendarView#246]
FATAL EXCEPTION: main
                                                                            Process: sundeepk.github.com.sample, PID: 12733
                                                                            java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                at java.util.ArrayList.get(ArrayList.java:411)
                                                                                at com.github.sundeepk.compactcalendarview.CompactCalendarController.drawEvents(CompactCalendarController.java:771)
                                                                                at com.github.sundeepk.compactcalendarview.CompactCalendarController.drawMonth(CompactCalendarController.java:835)
                                                                                at com.github.sundeepk.compactcalendarview.CompactCalendarController.drawCurrentMonth(CompactCalendarController.java:707)
                                                                                at com.github.sundeepk.compactcalendarview.CompactCalendarController.drawScrollableCalender(CompactCalendarController.java:695)
                                                                                at com.github.sundeepk.compactcalendarview.CompactCalendarController.onDraw(CompactCalendarController.java:426)
                                                                                at com.github.sundeepk.compactcalendarview.CompactCalendarView.onDraw(CompactCalendarView.java:390)

**Comment by SundeepK** [comment]
Hi, is there an example of what you were doing when this happened? Did you call the removeEvent, and saw this error?

**Comment by acolombo25** [comment]
The same happens to me when I remove the last event of one day. If one day has more than one event it can be removed without problems, but if an event has only one day, removing it causes this crash when the Calendar is getting re-drawn.

**Comment by acolombo25** [comment]
I've been able to reproduce the issue on the sample project.
It only happens when the event indicator style attribute is set to fill_large:
`app:compactCalendarEventIndicatorStyle="fill_large_indicator"`

Add an additional button in the layout and set this listener at the end of onCreateView
`removeButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                List<Event> events = compactCalendarView.getEventsForMonth((Calendar.getInstance()).getTime());
                compactCalendarView.removeEvent(events.get(1), true);

            }
        });`
When you'll click the button, which tries to remove the event on the 2nd day of the month, the sample app crashes.

**Comment by acolombo25** [comment]
I've fixed the issue in pull request #247, commit 851a0ac999420c65034f953c2ab49c2d1a28f8e5

**Comment by SundeepK** [comment]
@acolombo25 I've made some additional on top of your pr. If you want to can checkout branch 246_fix_exception_on_rendering_no_events and test it out to see if the problem is fixed. let me know if this is something you can do.

**Comment by acolombo25** [comment]
Sure! I'll let you know in a few hours.

**Comment by SundeepK** [comment]
Thanks, I've had a chance to also test it and it should be working as expected. I've ran all the tests locally no failures. But I'll be releasing a new version tomorrow as it's getting late here.

**Comment by SundeepK** [comment]
New versions been released will update readme soon with the version.
