### ISSUE TITLE
Get Event from location not work

### ISSUE THREAD

**Issue by sugeivan** [SundeepK/CompactCalendarView#74]
List<Event> events = compactCalendarView.getEvents(date);

        Event eventDetail=events.get(2);

        String txtevent=eventDetail.toString();
        showEvent.setText(txtevent);

//////////////////////////////////////////////////////////////////////////////////////////////////
06-06 19:08:24.008 19158-19158/iqueueboxlk.com.calender E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: iqueueboxlk.com.calender, PID: 19158
                                                                          java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
                                                                              at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                              at java.util.ArrayList.get(ArrayList.java:308)
                                                                              at iqueueboxlk.com.calender.MainActivity.getevent(MainActivity.java:97)
                                                                              at iqueueboxlk.com.calender.MainActivity$3.onClick(MainActivity.java:73)
                                                                              at android.view.View.performClick(View.java:5076)
                                                                              at android.view.View$PerformClick.run(View.java:20279)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5930)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
06-06 19:08:25.658 19158-19158/iqueueboxlk.com.calender I/Process: Sending signal. PID: 19158 SIG: 9

**Comment by SundeepK** [comment]
Thats because there is only one item in your list, so an exception is thrown because your trying to a get on an invalid index location.

**Comment by sugeivan** [comment]
ok sir, now I got it
can we put circle background to the event day?

**Comment by SundeepK** [comment]
Currently no there is now method for this, however you can fork the code and easily draw a circle around the event day if you want to.
